---

# file: playbook.yml

- hosts: development
  sudo: yes
  gather_facts: no
  roles:
      - postgres

- hosts: development
  sudo: yes
  sudo_user: postgres
  gather_facts: no
  roles:
      - database

- hosts: development
  sudo: yes
  gather_facts: no
  roles:
      - dropbox_backup
