---

# file: roles/dropbox_backup/tasks/backup_setup.yml

- name: Create backups directories
  file: path={{item}} state=directory mode=0755
  with_items:
    - "{{dropbox_backup.uploader_script_folder}}"
    - "{{dropbox_backup.directory}}"
    - "{{dropbox_backup.configuration_folder}}"
  tags:
    - backup

- name: Download dropbox_uploader
  get_url: url=https://raw.githubusercontent.com/andreafabrizi/Dropbox-Uploader/master/dropbox_uploader.sh dest={{dropbox_backup.uploader_script_folder}}/dropbox_uploader.sh mode=0755
  tags:
    - backup

- name: Copy dropbox configuration file
  copy: src=.dropbox_uploader dest="{{dropbox_backup.configuration_folder}}/.dropbox_uploader" mode=0600
  tags:
    - backup

- name: Copy dropbox script
  template: src=backup.sh dest="{{dropbox_backup.configuration_folder}}/backup.sh" mode=0600
  tags:
    - backup

- name: Create cron job to perform five minute backups
  cron: name="Dropbox backups" minute="*/5" hour="*" job="sh "{{dropbox_backup.configuration_folder}}"/backup.sh >> /var/log/backup.log 2>&1"
  tags:
    - backup
